// libs/shared/apollo/react/cdk/src/v3/components/layout/components/nav/nav-disclosure.tsx
import { useCallback, useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { twJoin } from '../../../../utils';
import { Icon } from '../../../icon';
import { LayoutFeature, LayoutNavigationItem } from '../../layout.model';
import { getActiveChild } from '../../layout.utils';
import { NavIcon } from './nav-icon';
import { NavItem } from './nav-item';

export interface NavDisclosureProps {
  item: LayoutNavigationItem;
  beta?: LayoutFeature;
  onItemSelect: (item: LayoutNavigationItem) => void;
}

export const NavDisclosure = ({ item, beta, onItemSelect }: NavDisclosureProps) => {
  const [open, setOpen] = useState(false);
  const [activeChild, setActiveChild] = useState<LayoutNavigationItem | null>(null);
  const { pathname } = useLocation();

  const handleItemSelect = useCallback(
    (item: LayoutNavigationItem) => {
      setOpen(false);
      item.trackEvent?.();
      onItemSelect(item);
    },
    [onItemSelect]
  );
  const visibleChildren = useCallback(() => {
    const isChildVisible = (child: LayoutNavigationItem) => child.visible;
    return item.children?.filter(isChildVisible) || [];
  }, [item]);

  useEffect(() => {
    const updateActiveChild = (url: string) => {
      setActiveChild(item.children ? getActiveChild(url, item.children) : null);
    };

    updateActiveChild(pathname);
  }, [pathname, item.children]);

  return (
    <div>
      <button
        type="button"
        className={twJoin(
          'tw-flex tw-w-full tw-items-center tw-px-4 tw-py-2 tw-text-left rtl:tw-text-right',
          'hover:tw-bg-[rgb(from_var(--apollo-layout-highlight)_r_g_b_/_15%)] hover:tw-text-[var(--apollo-layout-highlight)]',
          'focus:tw-bg-[rgb(from_var(--apollo-layout-highlight)_r_g_b_/_15%)] focus:tw-text-[var(--apollo-layout-highlight)] focus:tw-outline-none',
          'active:tw-bg-[rgb(from_var(--apollo-layout-highlight)_r_g_b_/_30%)] active:tw-text-[var(--apollo-layout-highlight)]'
        )}
        data-dgat={item.dgat}
        hidden={visibleChildren().length === 0}
        onClick={() => setOpen((open) => !open)}
      >
        <NavIcon item={item} active={activeChild !== null} className="tw-size-6 tw-shrink-0 tw-mr-2 rtl:tw-mr-0 rtl:tw-ml-2" />

        <span className={twJoin(beta?.enabled && item.isBeta ? '' : 'tw-grow')}>{item.text}</span>

        {beta?.enabled && item.isBeta ? (
          <div className={twJoin('tw--mt-2 tw-flex tw-grow tw-self-start')}>
            <div
              className={twJoin(
                'tw-rounded-2xl tw-border tw-border-purple-300 tw-bg-purple-100 tw-px-1 tw-py-0.5 tw-text-[8px] tw-font-extrabold tw-uppercase tw-leading-3 tw-text-purple-800'
              )}
            >
              {beta.text}
            </div>
          </div>
        ) : null}

        <Icon
          icon="chevron-right"
          type="solid"
          solidSize="16"
          className={twJoin('tw-size-4 tw-ml-2 rtl:tw-ml-0 rtl:tw-mr-2', open ? 'tw-rotate-90' : 'rtl:tw-rotate-180')}
        />
      </button>

      {open ? (
        <div>
          <ul className="tw-flex tw-flex-col">
            {visibleChildren()
              ?.filter((child) => child.href || child.routerLink)
              .map((child) => (
                <li key={child.dgat}>
                  <NavItem
                    item={child}
                    active={child === activeChild}
                    onItemSelect={() => handleItemSelect(child)}
                    className="tw-px-12 tw-text-base"
                  ></NavItem>
                </li>
              ))}
          </ul>
        </div>
      ) : null}

      {!open && activeChild && (activeChild.href || activeChild.routerLink) ? (
        <ul>
          <li>
            <NavItem
              item={activeChild}
              active
              onItemSelect={() => handleItemSelect(activeChild)}
              className="tw-px-12 tw-text-base"
            ></NavItem>
          </li>
        </ul>
      ) : null}
    </div>
  );
};

// libs/shared/apollo/angular/src/lib/components/layout/components/nav/nav-disclosure.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

import { Router } from '@angular/router';
import { LayoutNavigationItem } from '../../layout.model';
import { getActiveSubItem } from '../../layout.utils';

@Component({
  selector: 'da-nav-disclosure',
  template: `
    <div>
      <button
        type="button"
        [class]="
          [
            'tw-flex tw-w-full tw-items-center tw-gap-2 tw-px-4 tw-py-2 tw-text-left',
            'hover:tw-bg-[rgb(from_var(--apollo-layout-highlight,theme(colors.neutral.800))_r_g_b_/_15%)] hover:tw-text-[var(--apollo-layout-highlight,theme(colors.neutral.800))]',
            'focus:tw-bg-[rgb(from_var(--apollo-layout-highlight,theme(colors.neutral.800))_r_g_b_/_15%)] focus:tw-text-[var(--apollo-layout-highlight,theme(colors.neutral.800))] focus:tw-outline-none',
            'active:tw-bg-[rgb(from_var(--apollo-layout-highlight,theme(colors.neutral.900))_r_g_b_/_30%)] active:tw-text-[var(--apollo-layout-highlight,theme(colors.neutral.900))]',
          ].join(' ')
        "
        [attr.data-dgat]="item.dgat"
        (click)="open = !open"
      >
        <da-nav-icon [item]="item" [active]="!!activeChild" className="tw-size-6 tw-shrink-0" />
        <span class="tw-grow">{{ item.text }}</span>
        <da-icon icon="chevron-right" type="solid" [solidSize]="16" [className]="['tw-size-4', open ? 'tw-rotate-90' : ''].join(' ')" />
      </button>

      <div *ngIf="open">
        <ul class="tw-flex tw-flex-col">
          <li *ngFor="let subItem of item.subItems">
            <ng-container *ngIf="subItem.href || subItem.routerLink">
              <da-nav-item [item]="subItem" (itemSelect)="handleItemSelect()" className="tw-px-12 tw-text-base"></da-nav-item>
            </ng-container>
          </li>
        </ul>
      </div>

      <ul *ngIf="!open && activeChild && (activeChild.href || activeChild.routerLink)">
        <li>
          <da-nav-item [item]="activeChild" (itemSelect)="handleItemSelect()" className="tw-px-12 tw-text-base"></da-nav-item>
        </li>
      </ul>
    </div>
  `,
})
export class NavDisclosureComponent implements OnInit {
  @Input() item!: LayoutNavigationItem;
  @Output() itemSelect = new EventEmitter<void>();

  open = false;
  activeChild: LayoutNavigationItem | null = null;

  constructor(private router: Router) {}

  ngOnInit(): void {
    this.setActiveChild(this.router.url);
  }

  handleItemSelect() {
    this.open = false;
    this.itemSelect.emit();
  }

  private setActiveChild(pathname: string) {
    if (this.item.subItems) {
      this.activeChild = getActiveSubItem(pathname, this.item.subItems);
    }
  }
}
