// src/components/layout/components/nav-item.tsx
import { NavLink } from 'react-router-dom';
import { twMerge } from 'tailwind-merge';

import { DynamicIcon } from '../../dynamic-icon';

export interface NavItemProps {
  label: string;
  icon?: string;
  path: string;
  iconOnly?: boolean;
  className?: string;
  onClick?: () => void;
}

export const NavItem = ({
  label,
  icon,
  path,
  iconOnly,
  className,
  onClick,
}: NavItemProps) => {
  if (!icon) iconOnly = false;

  return (
    <NavLink
      to={path}
      className={twMerge(
        'flex items-center gap-2 px-7 py-2 focus:outline-none',
        'hover:bg-[rgb(from_var(--layout-highlight,theme(colors.neutral.800))_r_g_b_/_15%)] hover:text-[var(--layout-highlight,theme(colors.neutral.800))]',
        'focus:bg-[rgb(from_var(--layout-highlight,theme(colors.neutral.800))_r_g_b_/_15%)] focus:text-[var(--layout-highlight,theme(colors.neutral.800))]',
        'active:bg-[rgb(from_var(--layout-highlight,theme(colors.neutral.900))_r_g_b_/_30%)] active:text-[var(--layout-highlight,theme(colors.neutral.900))]',
        className,
      )}
      onClick={onClick}
    >
      {icon ? (
        <DynamicIcon
          icon={icon}
          type="solid"
          className="size-6 shrink-0"
          aria-hidden="true"
        />
      ) : null}
      <span className={iconOnly ? 'sr-only' : 'grow'}>{label}</span>
    </NavLink>
  );
};

// apps/playground-angular/src/components/layout/components/nav-item.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { RouterModule } from '@angular/router';
import { twMerge } from 'tailwind-merge';
import { IconsModule } from '../../../lib/icons';

@Component({
  selector: 'app-nav-item',
  template: `
    <a [routerLink]="path" [ngClass]="mergedClasses" (click)="handleClick()">
      <ng-container *ngIf="icon">
        <app-dynamic-icon
          [icon]="icon"
          type="solid"
          className="size-6 shrink-0"
        ></app-dynamic-icon>
      </ng-container>
      <span [ngClass]="{ 'sr-only': iconOnly, grow: !iconOnly }">{{
        label
      }}</span>
    </a>
  `,
  standalone: true,
  imports: [CommonModule, RouterModule, IconsModule],
})
export class NavItemComponent {
  @Input() label!: string;
  @Input() icon?: string;
  @Input() path!: string;
  @Input() iconOnly?: boolean = false;
  @Input() className = '';
  @Output() itemSelect = new EventEmitter<void>();

  get mergedClasses(): string {
    return twMerge(
      'flex items-center gap-2 px-7 py-2 focus:outline-none',
      'hover:bg-[rgb(from_var(--layout-highlight,theme(colors.neutral.800))_r_g_b_/_15%)] hover:text-[var(--layout-highlight,theme(colors.neutral.800))]',
      'focus:bg-[rgb(from_var(--layout-highlight,theme(colors.neutral.800))_r_g_b_/_15%)] focus:text-[var(--layout-highlight,theme(colors.neutral.800))]',
      'active:bg-[rgb(from_var(--layout-highlight,theme(colors.neutral.900))_r_g_b_/_30%)] active:text-[var(--layout-highlight,theme(colors.neutral.900))]',
      this.className,
    );
  }

  handleClick() {
    this.itemSelect.emit();
  }
}
