// apps/playground-angular/src/components/layout/layout.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  EventEmitter,
  Inject,
  Input,
  OnInit,
  Output,
} from '@angular/core';
import { RouterModule, RouterOutlet } from '@angular/router';
import { HeaderComponent } from './components/header.component';
import { SidebarComponent } from './components/sidebar.component';
import { defaultConfiguration } from './default.config';
import {
  LayoutConfiguration,
  LayoutConfigurationToken,
  LayoutTheme,
} from './layout.model';

@Component({
  selector: 'app-layout',
  template: `
    <div
      [style]="{
        '--layout-background': theme?.colors?.background,
        '--layout-text':
          theme?.text === 'light' ? 'white' : 'var(--tw-color-neutral-800)',
        '--layout-highlight': theme?.colors?.highlight
      }"
    >
      <!-- Skip To Main Content Link -->
      <a href="#main-content" class="sr-only">Skip to main content</a>

      <!-- Header -->
      <app-header
        [logos]="configuration?.logos"
        [features]="configuration?.features"
        [navigation]="configuration?.navigation"
        [className]="
          [
            'transition-[margin]',
            sidebarExpanded ? 'lg:ml-52' : 'lg:ml-20'
          ].join(' ')
        "
        (search)="handleSearch($event)"
        (themeChange)="setTheme($event)"
      ></app-header>

      <!-- Sidebar -->
      <app-sidebar
        [logos]="configuration?.logos"
        [features]="configuration?.features"
        [navigation]="configuration?.navigation"
        [sidebarExpanded]="sidebarExpanded"
        [className]="
          ['transition-[width]', sidebarExpanded ? 'lg:w-52' : 'lg:w-20'].join(
            ' '
          )
        "
        (toggleExpanded)="toggleSidebar()"
        (add)="handleAdd($event)"
      ></app-sidebar>

      <!-- Main Content -->
      <main
        id="main-content"
        class="flex min-h-dvh flex-col px-4 pb-4 pt-20 transition-[margin] lg:px-8"
        [class]="sidebarExpanded ? 'lg:ml-52' : 'lg:ml-20'"
      >
        <section class="grow">
          <ng-content></ng-content>
          <router-outlet></router-outlet>
        </section>

        <!-- Footer -->
        <footer class="grid h-20 place-content-center">Footer</footer>
      </main>
    </div>
  `,
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    HeaderComponent,
    SidebarComponent,
    RouterOutlet,
  ],
})
export class LayoutComponent implements OnInit {
  @Input() configuration?: LayoutConfiguration;
  @Output() search = new EventEmitter<MouseEvent>();
  @Output() add = new EventEmitter<MouseEvent>();

  theme?: LayoutTheme;
  sidebarExpanded = false;

  constructor(
    @Inject(LayoutConfigurationToken)
    private providedConfiguration: LayoutConfiguration,
  ) {}

  ngOnInit(): void {
    this.configuration = {
      ...defaultConfiguration,
      ...this.providedConfiguration,
      ...this.configuration,
    };
    this.theme = this.configuration?.theme;
  }

  handleSearch(event: MouseEvent): void {
    this.search.emit(event);
  }

  handleAdd(event: MouseEvent): void {
    this.add.emit(event);
  }

  setTheme(theme: LayoutTheme): void {
    this.theme = theme;
  }

  toggleSidebar(): void {
    this.sidebarExpanded = !this.sidebarExpanded;
  }
}

// src/components/layout/layout.tsx
import clsx from 'clsx';
import { ReactNode, useState } from 'react';

import { Outlet } from 'react-router-dom';
import { EventBus, inject } from '../../lib';
import { Header, Sidebar } from './components';
import { defaultConfiguration } from './default.config';
import {
  LayoutConfiguration,
  LayoutConfigurationToken,
  LayoutTheme,
} from './layout.model';

export interface LayoutProps {
  configuration?: LayoutConfiguration;
  children: ReactNode;
  onSearch?: React.MouseEventHandler<HTMLButtonElement>;
  onAdd?: React.MouseEventHandler<HTMLButtonElement>;
}

export const Layout = ({
  configuration,
  children,
  onSearch,
  onAdd,
}: LayoutProps) => {
  const providedConfiguration = inject<LayoutConfiguration>(
    LayoutConfigurationToken,
  );

  configuration = {
    ...defaultConfiguration,
    ...providedConfiguration,
    ...configuration,
  };
  const { logos, features, navigation } = configuration;
  const [theme, setTheme] = useState<LayoutTheme | undefined>(
    configuration.theme,
  );

  const [sidebarExpanded, setSidebarExpanded] = useState(false);
  const eventBus = inject<EventBus>(EventBus);

  const handleSearch: React.MouseEventHandler<HTMLButtonElement> = (e) => {
    eventBus?.announce({ type: 'search', data: e });
    onSearch?.(e);
  };
  const handleAdd: React.MouseEventHandler<HTMLButtonElement> = (e) => {
    eventBus?.announce({ type: 'add', data: e });
    onAdd?.(e);
  };

  return (
    <div
      style={
        {
          '--layout-background': theme?.colors.background,
          '--layout-text':
            theme?.text === 'light' ? 'white' : 'var(--tw-color-neutral-800)',
          '--layout-highlight': theme?.colors.highlight,
        } as React.CSSProperties
      }
    >
      {/* Skip To Main Content Link */}
      <a href="#main-content" className="sr-only">
        Skip to main content
      </a>

      {/* Header */}
      <Header
        logos={logos}
        features={features}
        navigation={navigation}
        className={clsx(
          'transition-[margin]',
          sidebarExpanded ? 'lg:ml-52' : 'lg:ml-20',
        )}
        onSearch={handleSearch}
        onThemeChange={setTheme}
      />

      {/* Sidebar */}
      <Sidebar
        logos={logos}
        features={features}
        navigation={navigation}
        sidebarExpanded={sidebarExpanded}
        className={clsx(
          'transition-[width]',
          sidebarExpanded ? 'lg:w-52' : 'lg:w-20',
        )}
        onToggleExpanded={() =>
          setSidebarExpanded((sidebarExpanded) => !sidebarExpanded)
        }
        onAdd={handleAdd}
      />

      {/* Main Content */}
      <main
        id="main-content"
        className={clsx(
          'flex min-h-dvh flex-col px-4 pb-4 pt-20 transition-[margin] lg:px-8',
          sidebarExpanded ? 'lg:ml-52' : 'lg:ml-20',
        )}
      >
        <section className="grow">{children ?? <Outlet />}</section>

        {/* Footer */}
        <footer className="grid h-20 place-content-center">Footer</footer>
      </main>
    </div>
  );
};
