// src/components/layout/components/sidebar.tsx
import {
  Disclosure,
  DisclosureButton,
  DisclosurePanel,
} from '@headlessui/react';
import { ChevronRightIcon, PlusIcon } from '@heroicons/react/20/solid';
import clsx from 'clsx';

import { LayoutFeatures, LayoutLogos, LayoutNavigation } from '../layout.model';
import { NavItem } from './nav-item';
import { NavPopover } from './nav-popover';

export interface SidebarProps {
  logos?: LayoutLogos;
  features?: LayoutFeatures;
  navigation?: LayoutNavigation;
  sidebarExpanded: boolean;
  className?: string;
  onToggleExpanded: () => void;
  onAdd?: React.MouseEventHandler<HTMLButtonElement>;
}

export const Sidebar = ({
  logos,
  features,
  navigation,
  sidebarExpanded,
  className,
  onToggleExpanded,
  onAdd,
}: SidebarProps) => {
  return (
    <>
      {/* Sidebar */}
      <Disclosure
        as="aside"
        className={clsx(
          'fixed inset-y-0 left-0 hidden shadow lg:block',
          'bg-[var(--layout-background,white)] text-[var(--layout-text,theme(colors.neutral.800))]',
          className,
        )}
        defaultOpen={sidebarExpanded}
      >
        {/* Sidebar Expand Button */}
        <DisclosureButton
          id="sidebar-expand-button"
          className={clsx(
            'absolute -right-4 top-4',
            'rounded-md bg-white p-1.5 text-sm font-semibold text-neutral-900 shadow-lg ring-1 ring-inset ring-neutral-300',
            'hover:bg-neutral-50 focus:bg-neutral-50 focus:outline-none active:bg-neutral-100',
          )}
          title={sidebarExpanded ? 'Collapse Sidebar' : 'Expand Sidebar'}
          onClick={onToggleExpanded}
        >
          <ChevronRightIcon
            className={clsx('size-4', sidebarExpanded ? 'rotate-180' : '')}
            aria-hidden="true"
          />
          <span className="sr-only">
            {sidebarExpanded ? 'Collapse Sidebar' : 'Expand Sidebar'}
          </span>
        </DisclosureButton>

        <DisclosurePanel static>
          {({ open }) => (
            <>
              {/* Logos */}
              {logos ? (
                <div className="grid h-20 place-content-center overflow-hidden">
                  {sidebarExpanded ? (
                    <div className="flex">
                      <img src={logos.logo.url} alt="Logo" className="h-10" />
                    </div>
                  ) : (
                    <img src={logos.mark.url} alt="Logo" className="size-10" />
                  )}
                  <span className="sr-only">Logo</span>
                </div>
              ) : null}

              <div
                className={clsx(
                  'fixed bottom-0 left-0 top-20 overflow-y-auto overflow-x-hidden pb-4 transition-[width]',
                  open ? 'w-52' : 'w-20',
                )}
              >
                {/* Sidebar Navigation */}
                {navigation ? (
                  <nav className="flex h-full flex-col">
                    <ul className="flex flex-col">
                      {navigation.top.map((item, index) => (
                        <li key={index}>
                          {item.path ? (
                            <NavItem
                              {...item}
                              path={item.path}
                              iconOnly={!sidebarExpanded}
                            />
                          ) : item.subItems?.length ? (
                            <NavPopover
                              {...item}
                              subItems={item.subItems}
                              iconOnly={!sidebarExpanded}
                            />
                          ) : null}
                        </li>
                      ))}
                    </ul>

                    {/* <Lipsum className="px-4" /> */}

                    <ul className="flex grow flex-col justify-end">
                      {features?.add ? (
                        <li className="py-2 text-center">
                          <button
                            type="button"
                            className={clsx(
                              'inline-flex items-center gap-0.5 whitespace-nowrap',
                              'rounded-md bg-white py-1.5 text-sm font-semibold text-neutral-900 shadow-lg ring-1 ring-inset ring-neutral-300',
                              'hover:bg-neutral-50 focus:bg-neutral-50 focus:outline-none active:bg-neutral-100',
                              '[&_*]:pointer-events-none',
                              sidebarExpanded ? 'px-2.5' : 'px-1.5',
                            )}
                            onClick={onAdd}
                          >
                            <PlusIcon className="size-4" aria-hidden="true" />
                            <span
                              className={clsx(sidebarExpanded ? '' : 'sr-only')}
                            >
                              Add
                            </span>
                          </button>
                        </li>
                      ) : null}
                      {navigation.bottom?.map((item, index) => (
                        <li key={index}>
                          {item.path ? (
                            <NavItem
                              {...item}
                              path={item.path}
                              iconOnly={!sidebarExpanded}
                            />
                          ) : item.subItems?.length ? (
                            <NavPopover
                              {...item}
                              subItems={item.subItems}
                              iconOnly={!sidebarExpanded}
                            />
                          ) : null}
                        </li>
                      ))}
                    </ul>
                  </nav>
                ) : null}
              </div>
            </>
          )}
        </DisclosurePanel>
      </Disclosure>
    </>
  );
};

// libs/shared/apollo/angular/src/lib/components/layout/components/sidebar.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

import { twMerge } from '../../../utils/tw-merge';
import { LayoutBrand, LayoutFeatures, LayoutNavigation } from '../layout.model';

@Component({
  selector: 'da-sidebar',
  template: `
    <!-- Sidebar -->
    <div
      [class]="
        twMerge(
          'tw-fixed tw-inset-y-0 tw-left-0 tw-shadow-lg',
          'tw-bg-[var(--apollo-layout-background,white)] tw-text-[var(--apollo-layout-text,theme(colors.neutral.800))]',
          className
        )
      "
    >
      <!-- Sidebar Expand Button -->
      <div class="tw-reset">
        <button
          type="button"
          class="tw-btn-icon tw-btn-secondary-outline tw-absolute -tw-right-3 tw-top-6 tw-shadow-lg"
          [title]="sidebarExpanded ? 'Collapse Menu' : 'Expand Menu'"
          (click)="handleToggleExpanded()"
        >
          <da-icon
            icon="chevron-right"
            type="solid"
            [solidSize]="16"
            [className]="twMerge('tw-size-4', sidebarExpanded ? 'tw-rotate-180' : '')"
          />
        </button>
      </div>

      <!-- Logos -->
      <a
        *ngIf="brand"
        [routerLink]="brand.homeUrl"
        data-dgat="product-header-5f2"
        class="tw-grid tw-h-20 tw-place-content-center tw-overflow-hidden focus-visible:tw-outline-none"
      >
        <ng-container *ngIf="sidebarExpanded; else markLogo">
          <img [src]="brand.logo.url" alt="Logo" class="tw-h-full tw-max-h-8 tw-max-w-[152px]" />
        </ng-container>
        <ng-template #markLogo>
          <img [src]="brand.mark.url" alt="Logo" class="tw-size-8" />
        </ng-template>
        <span class="tw-sr-only">Logo</span>
      </a>

      <div
        [class]="
          twMerge(
            'tw-fixed tw-bottom-0 tw-left-0 tw-top-20 tw-overflow-y-auto tw-overflow-x-hidden tw-pb-6 tw-transition-[width]',
            sidebarExpanded ? 'tw-w-[200px]' : 'tw-w-20'
          )
        "
      >
        <!-- Sidebar Navigation -->
        <nav *ngIf="navigation" class="tw-flex tw-h-full tw-flex-col">
          <ul class="tw-flex tw-flex-col">
            <li *ngFor="let item of navigation.top">
              <!-- Nav Item -->
              <ng-container *ngIf="item.href || item.routerLink">
                <da-nav-item [item]="item" [iconOnly]="!sidebarExpanded"></da-nav-item>
              </ng-container>

              <!-- Nav Popover -->
              <ng-container *ngIf="item.subItems?.length">
                <da-nav-popover [item]="item" [iconOnly]="!sidebarExpanded"></da-nav-popover>
              </ng-container>
            </li>
          </ul>

          <ul class="tw-flex tw-grow tw-flex-col tw-justify-end">
            <li *ngIf="features?.addContent?.enabled" class="tw-py-2 tw-text-center">
              <button
                type="button"
                [class]="twMerge('tw-btn-medium tw-btn-secondary-filled', sidebarExpanded ? '' : 'tw-btn-icon')"
                dgat="utilityBar-fab"
                (click)="handleAddContent($event)"
              >
                <da-icon icon="plus" type="solid" [solidSize]="16" className="tw-size-4" />
                <span [class]="sidebarExpanded ? 'tw-whitespace-nowrap' : 'tw-sr-only'">{{ features?.addContent?.text }}</span>
              </button>
            </li>
            <li *ngFor="let item of navigation.bottom">
              <!-- Nav Item -->
              <ng-container *ngIf="item.href || item.routerLink">
                <da-nav-item [item]="item" [iconOnly]="!sidebarExpanded"></da-nav-item>
              </ng-container>

              <!-- Nav Popover -->
              <ng-container *ngIf="item.subItems?.length">
                <da-nav-popover [item]="item" [iconOnly]="!sidebarExpanded"></da-nav-popover>
              </ng-container>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  `,
})
export class SidebarComponent {
  @Input() brand?: LayoutBrand;
  @Input() features?: LayoutFeatures;
  @Input() navigation?: LayoutNavigation;
  @Input() sidebarExpanded = false;
  @Input() className = '';
  @Output() toggleExpanded = new EventEmitter<void>();
  @Output() addContent = new EventEmitter<MouseEvent>();

  twMerge = twMerge;

  handleToggleExpanded() {
    this.toggleExpanded.emit();
  }

  handleAddContent(event: MouseEvent) {
    this.addContent.emit(event);
  }
}
